config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq-scheduler/web"

Rails.application.routes.draw do
  resources :users, only: [] do
    collection do
      get "/current" => "users#current", :constraints => {format: "json"}
    end
  end

  get "/thank-you" => "static_pages#thank_you"

  # User Profile
  match "/profile" => "user_profiles#edit", :via => :get, :as => :user_profile
  match "/profile" => "user_profiles#update", :via => [:put, :patch]

  # User Membership
  match "/membership" => "memberships#index", :via => :get, :as => :user_membership
  match "/membership/update_amount" => "memberships#update_amount", :via => [:put, :patch], :as => :update_membership_amount
  match "/membership/update_card" => "memberships#update_card", :via => [:put, :patch], :as => :update_membership_card
  match "/membership/pause" => "memberships#pause", :via => [:put, :patch], :as => :pause_membership
  match "/membership/resume" => "memberships#resume", :via => [:put, :patch], :as => :resume_membership

  # Funds
  match "/funds" => "funds#index", :via => :get

  resources :subscriptions, only: %i[create]
  resources :charges, only: %i[new create], path: "donate", path_names: {new: ""}

  resources :user_confirmations, only: %i[index create] do
    collection do
      post "/confirm" => "user_confirmations#confirm"

      get "/confirm_email/:email_token" => "user_confirmations#confirm_email_token", :as => "confirm_email_token"
      post "/confirm_email" => "user_confirmations#confirm_email", :as => "confirm_email"
    end
  end

  get "/login" => "sessions#login"

  if Rails.env.production?
    mount Sidekiq::Web => "/sidekiq",
          :constraints => AdminConstraint.new(require_master: true)
  else
    mount Sidekiq::Web => "/sidekiq"
  end

  root to: "dashboard#index"
end

# test routes for cypress
unless Rails.env.production?
  Rails.application.routes.append do
    match "/test/widget/donation" => "test_pages#widget_donation", :via => [:get]
    match "/test/widget/membership" => "test_pages#widget_membership", :via => [:get]
    scope path: "/__cypress__", controller: "cypress" do
      post "force_login", action: "force_login"
    end
  end
end

app/controllers/memberships_controller.rb
# frozen_string_literal: true

class MembershipsController < HubController
  before_action :set_membership

  def index
  end

  def edit_amount
  end

  def update_amount
    amount_params = params.require(:membership).permit(:amount)
    @membership.assign_attributes(amount_params)

    respond_to do |format|
      if @membership.save
        format.html do
          flash[:success] = "Amount changed and it will be effective on your next billing"

          redirect_to action: :index
        end
      else
        format.html do
          flash[:error] = "There were errors updating your membership"

          render :index
        end
      end
    end
  end

  def edit_card
  end

  def update_card
    card_updated = @membership.update_credit_card!(update_card_params)

    if !card_updated
      respond_to do |format|
        format.json do
          flash[:error] = I18n.t("memberships.update_card.error")

          render json: {status: "failed", redirect_to: user_membership_path}, status: :unprocessable_entity
        end
      end

      return
    end

    if !@membership.should_charge?
      respond_to do |format|
        format.json do
          flash[:success] = I18n.t("memberships.update_card.next_cycle")

          render json: {status: "succeeded", redirect_to: user_membership_path}, status: :ok
        end
      end

      return
    end

    respond_to do |format|
      if @membership.charge!
        format.json do
          flash[:success] = I18n.t("memberships.update_card.paid")

          render json: {status: "succeeded", redirect_to: user_membership_path}, status: :ok
        end
      else
        format.json do
          flash[:error] = I18n.t("memberships.update_card.error")

          render json: {status: "failed", redirect_to: user_membership_path}, status: :unprocessable_entity
        end
      end
    end
  end

  def edit_status
  end

  def pause
    respond_to do |format|
      if @membership.paused!
        format.html do
          flash[:success] = "Your membership is now paused"

          redirect_to action: :index
        end
      else
        format.html do
          flash[:error] = "There were errors updating your membership"

          render :edit_status
        end
      end
    end
  end

  def resume
    respond_to do |format|
      if @membership.active!
        format.html do
          flash[:success] = "Your membership is now active"

          redirect_to action: :index
        end
      else
        format.html do
          flash[:error] = "There were errors updating your membership"

          render :edit_status
        end
      end
    end
  end

  private

  def set_membership
    @membership = current_user.subscription
  end

  def update_card_params
    params.require(:membership).permit(
      :address_city,
      :address_country_code,
      :address_line1,
      :address_state,
      :address_zip,
      :first_name,
      :last_name,
      :stripe_card_id,
      :stripe_card_last4,
      :stripe_token
    )
  end
end

app/views/memberships/_edit_amount_form.html.erb
<%= form_with(model: membership, url: update_membership_amount_path, builder: ApplicationFormBuilder, local: true, class: "w-full sm:w-1/2") do |f| %>
<!-- List form errors -->
  <% if membership.errors.any? %>
  <div class="p-4 rounded-md bg-red-50">
    <div class="flex">
      <div class="flex-shrink-0">
        <!-- Heroicon name: solid/x-circle -->
        <svg class="w-5 h-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
        </svg>
      </div>
      <div class="ml-3">
        <h3 class="text-sm font-medium text-red-800">
          <%= pluralize(membership.errors.count, "error") %> with your submission
        </h3>
        <div class="mt-2 text-sm text-red-700">
          <ul class="pl-5 space-y-1 list-disc">
            <% membership.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <% end %>

  <div class="flex justify-between w-full">
    <span class="input-green flex items-center text-4xl sm:text-5xl font-black shadow-sm flex items-start pl-2 pr-4 py-2">$
      <%= f.number_field :amount, name: 'membership[amount]', id: 'membership_amount', min: 0, step: 1, value: number_to_currency(f.object.amount.to_f, unit: '', precision: 0),
      class: "w-full border-none bg-transparent text-4xl sm:text-5xl font-black h-full p-0 focus:ring-black focus:border-black", style: "" %>
    </span>
    <%= f.submit 'Save', class: "btn-green ml-2 inline-flex justify-center py-2 px-4 border border-transparent shadow-sm font-bold rounded-md text-white hover:bg-gray-900 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-lilac" %>
  </div>
<% end %>

app/views/memberships/_edit_card.html.erb
<div class="edit-card mb-20">
  <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between">
    <div class="sm:w-1/2">
      <p class="font-black text-gray-900 leading-tight" style="font-size:1.75rem">Current payment method</p>
      <p class="text-sm sm:text-base my-2">
        Card ending in <%= @membership.card_last4%>
      </p>
    </div>
    <!-- List form errors -->
    <% if membership.errors.any? %>
      <div class="p-4 rounded-md bg-red-50">
        <div class="flex">
          <div class="flex-shrink-0">
            <!-- Heroicon name: solid/x-circle -->
            <svg class="w-5 h-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
            </svg>
          </div>
          <div class="ml-3">
            <h3 class="text-sm font-medium text-red-800">
              There were <%= pluralize(membership.errors.count, "error") %> with your submission
            </h3>
            <div class="mt-2 text-sm text-red-700">
              <ul class="pl-5 space-y-1 list-disc">
                <% membership.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    <% end %>

    <%= react_component("UpdateCreditCardForm", {
      action: update_membership_card_path,
      method: 'put',
      authenticityToken: form_authenticity_token,
      countryOptions: country_options,
    }, {class: 'w-full sm:w-1/2'}) %>
  </div>
</div>
<% content_for :head do %>
<script type='text/javascript'>
  window.App = {
    STRIPE_PUBLISHABLE_KEY: '<%= ENV.fetch('STRIPE_PUBLISHABLE_KEY') %>'
  };
</script>
<% end %>

app/views/memberships/_pause_membership.html.erb
<div class="w-full flex flex-col sm:flex-row justify-between sm:justify-between sm:items-center">
  <p class="font-black text-gray-900 leading-loose" style="font-size:1.75rem">Your membership is</p>
  <div class="flex items-center justify-between w-full sm:w-1/2 sm:pl-2">
    <span class="btn-green inline-flex justify-center px-8 py-1 font-bold">
      Active
    </span>
    <%= form_with(model: @membership, url: pause_membership_path, builder: ApplicationFormBuilder, local: true, class: 'flex justify-end') do |f| %>
      <%= f.submit 'Pause subscription',
        class: "sm:max-w-max inline-flex bg-transparent border-none underline hover:no-underline justify-center py-4 text-md sm:text-lg font-thin focus:outline-none",
        data: { confirm: 'Are you sure?' }
      %>
    <% end %>
  </div>
</div>

app/views/memberships/_resume_membership.html.erb
<div class="w-full flex flex-col sm:flex-row justify-between sm:justify-between sm:items-center">
  <p class="font-black text-gray-900 leading-loose" style="font-size:1.75rem">Your membership is</p>
  <div class="flex items-center justify-between w-full sm:w-1/2 sm:pl-2">
    <span class="sm:max-w-max inline-flex bg-transparent border-none underline hover:no-underline justify-center py-4 text-md sm:text-lg font-thin focus:outline-none">
      Inactive
    </span>
    <%= form_with(model: @membership, url: resume_membership_path, builder: ApplicationFormBuilder, local: true, class: 'flex justify-end') do |f| %>
      <%= f.submit 'Resume subscription',
        class: "btn-green inline-flex px-2 py-2 font-bold text-md ml-2 sm:max-w-max hover:bg-gray-900",
        data: { confirm: 'Are you sure?' }
      %>
    <% end %>
  </div>
</div>

app/views/memberships/index.html.erb
<div class="membership content mb-20 md:-ml-4">
  <div class="pb-5 border-b border-gray-200">
    <h3 class="font-black text-black text-4xl sm:text-6xl">
      Membership
    </h3>
    <p class="max-w-2xl mt-2 text-xl sm:text-2xl font-thin mt-4 mb-10 leading-normal" style="color:#232323">Make changes to your membership!
    </p>
  </div>

  <!-- Membership -->
  <% if @membership.present? %>

  <section aria-labelledby="membership_status">
    <div class="mt-10">
      <% if @membership.paused? %>
        <%= render "resume_membership" %>
      <% else %>
        <%= render "pause_membership" %>
      <% end %>
    </div>
  </section>

  <section aria-labelledby="membership_amount">
    <div class="mt-8">
      <div class="flex flex-col sm:flex-row items-start justify-between">
        <p class="font-black text-gray-900 leading-tight sm:w-1/2  sm:mr-3" style="font-size:1.75rem">Your current monthly donation amount is</p>
        <%= render 'edit_amount_form', membership: @membership %>
      </div>

      <% if @membership.active? %>
      <p class="max-w-4xl mt-2 text-gray-900 text-md">Your next payment is due on <%= @membership&.next_payment_due_at.strftime("%b, %e") %></p>
      <% end %>
    </div>
  </section>

  <section aria-labelledby="membership_credit_card">
    <div class="mt-10">
      <%= render 'edit_card', membership: @membership %>
    </div>
  </section>

  <% else %>
  <section aria-labelledby="membership_amount">
    <div class="mt-8">
      <p class="max-w-4xl mt-2 text-lg text-gray-900">You haven't started your membership. <a class="font-medium text-blue-700 hover:text-blue-600" href="<%= "#{ENV["HOME_PAGE_URL"]}/debt-union" %>">Click here to start one.</a></p>
    </div>
  </section>
  <% end %>
</div>