config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "sidekiq-scheduler/web"

Rails.application.routes.draw do
  resources :users, only: [] do
    collection do
      get "/current" => "users#current", :constraints => {format: "json"}
    end
  end

  get "/thank-you" => "static_pages#thank_you"

  # User Profile
  match "/profile" => "user_profiles#edit", :via => :get, :as => :user_profile
  match "/profile" => "user_profiles#update", :via => [:put, :patch]

  # User Membership
  match "/membership" => "memberships#index", :via => :get, :as => :user_membership
  match "/membership/update_amount" => "memberships#update_amount", :via => [:put, :patch], :as => :update_membership_amount
  match "/membership/update_card" => "memberships#update_card", :via => [:put, :patch], :as => :update_membership_card
  match "/membership/pause" => "memberships#pause", :via => [:put, :patch], :as => :pause_membership
  match "/membership/resume" => "memberships#resume", :via => [:put, :patch], :as => :resume_membership

  # Funds
  match "/funds" => "funds#index", :via => :get

  resources :subscriptions, only: %i[create]
  resources :charges, only: %i[new create], path: "donate", path_names: {new: ""}

  resources :user_confirmations, only: %i[index create] do
    collection do
      post "/confirm" => "user_confirmations#confirm"

      get "/confirm_email/:email_token" => "user_confirmations#confirm_email_token", :as => "confirm_email_token"
      post "/confirm_email" => "user_confirmations#confirm_email", :as => "confirm_email"
    end
  end

  get "/login" => "sessions#login"

  if Rails.env.production?
    mount Sidekiq::Web => "/sidekiq",
          :constraints => AdminConstraint.new(require_master: true)
  else
    mount Sidekiq::Web => "/sidekiq"
  end

  root to: "dashboard#index"
end

# test routes for cypress
unless Rails.env.production?
  Rails.application.routes.append do
    match "/test/widget/donation" => "test_pages#widget_donation", :via => [:get]
    match "/test/widget/membership" => "test_pages#widget_membership", :via => [:get]
    scope path: "/__cypress__", controller: "cypress" do
      post "force_login", action: "force_login"
    end
  end
end

app/views/shared/_analytics_scripts.html.erb
<!-- Google Analytics -->
<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', '<%= ENV['GA_MEASUREMENT_ID'] %>', 'auto');
ga('send', 'pageview');
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>
<!-- End Google Analytics -->

<!-- Amplitude Analytics -->
<script type="text/javascript">
  (function(e,t){var n=e.amplitude||{_q:[],_iq:{}};var r=t.createElement("script")
  ;r.type="text/javascript";r.async=true
  ;r.src="https://cdn.amplitude.com/libs/amplitude-4.5.2-min.gz.js"
  ;r.onload=function(){if(e.amplitude.runQueuedFunctions){
  e.amplitude.runQueuedFunctions()}else{
  console.log("[Amplitude] Error: could not load SDK")}}
  ;var i=t.getElementsByTagName("script")[0];i.parentNode.insertBefore(r,i)
  ;function s(e,t){e.prototype[t]=function(){
  this._q.push([t].concat(Array.prototype.slice.call(arguments,0)));return this}}
  var o=function(){this._q=[];return this}
  ;var a=["add","append","clearAll","prepend","set","setOnce","unset"]
  ;for(var u=0;u<a.length;u++){s(o,a[u])}n.Identify=o;var c=function(){this._q=[]
  ;return this}
  ;var l=["setProductId","setQuantity","setPrice","setRevenueType","setEventProperties"]
  ;for(var p=0;p<l.length;p++){s(c,l[p])}n.Revenue=c
  ;var d=["init","logEvent","logRevenue","setUserId","setUserProperties","setOptOut",
  "setVersionName","setDomain","setDeviceId","setGlobalUserProperties","identify",
  "clearUserProperties","setGroup","logRevenueV2","regenerateDeviceId","logEventWithTimestamp",
  "logEventWithGroups","setSessionId","resetSessionId"]
  ;function v(e){function t(t){e[t]=function(){
  e._q.push([t].concat(Array.prototype.slice.call(arguments,0)))}}
  for(var n=0;n<d.length;n++){t(d[n])}}v(n);n.getInstance=function(e){
  e=(!e||e.length===0?"$default_instance":e).toLowerCase()
  ;if(!n._iq.hasOwnProperty(e)){n._iq[e]={_q:[]};v(n._iq[e])}return n._iq[e]}
  ;e.amplitude=n})(window,document);

  amplitude.getInstance().init("<%= ENV['AMPLITUDE_API_KEY'] %>");
</script>
<!-- End Amplitude Analytics -->

<script>
  let currentUserId = <%= @current_user ? @current_user.id : 0 %>;
  amplitude.getInstance().setUserId(currentUserId !== 0 ? currentUserId : null);
</script>

app/views/shared/_chatwoot.html.erb
<!-- Chatwoot Integration -->
  <script>
    (function(d,t) {
      var BASE_URL="<%= ENV['CHATWOOT_BASE_URL'] %>";
      var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
      g.src=BASE_URL+"/packs/js/sdk.js";
      s.parentNode.insertBefore(g,s);
      g.onload=function(){
        window.chatwootSDK.run({
          websiteToken: '<%= ENV['CHATWOOT_TOKEN'] %>',
          baseUrl: BASE_URL,
        })
      }
      window.chatwootSettings = {
        type: 'expanded_bubble',
        launcherTitle: 'Chat with us'
      }
    })(document,"script");
  </script>
<!-- End Chatwoot Integration -->

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, msg| %>
  <div class="p-4 mb-10 rounded-md alert <%= "bg-#{flash_message_class(type)}-50" %>">
    <div class="flex">
      <div class="flex-shrink-0">
        <!-- Heroicon name: solid/check-circle -->
        <svg class="w-5 h-5 <%= "text-#{flash_message_class(type)}-400" %>" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
          <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
        </svg>
      </div>
      <div class="ml-3">
        <p class="text-sm font-medium <%= "text-#{flash_message_class(type)}-800" %>">
          <%= msg %>
        </p>
      </div>
      <div class="pl-3 ml-auto">
        <div class="-mx-1.5 -my-1.5">
          <button type="button" class="alert-close inline-flex <%= "bg-#{flash_message_class(type)}-50 text-#{flash_message_class(type)}-500 hover:bg-#{flash_message_class(type)}-100 focus:ring-offset-#{flash_message_class(type)}-50 focus:ring-#{flash_message_class(type)}-600" %> rounded-md p-1.5 focus:outline-none focus:ring-2 focus:ring-offset-2">
            <span class="sr-only">Dismiss</span>
            <!-- Heroicon name: solid/x -->
            <svg class="w-5 h-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd" />
            </svg>
          </button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div id="dc-header-container">
  <dc-header
    id="dc-header"
    community="<%= ENV['DISCOURSE_URL'] %>"
    homepage="<%= ENV['HOME_PAGE_URL'] %>"
    returnurl="<%= request.base_url %>">
  </dc-header>
</div>

app/views/shared/_sidebar.html.erb
<!-- top navbar for mobile -->
<div class="mobile-nav-container flex md:hidden">
  <nav class="flex flex-row w-full justify-evenly">
    <%= link_to root_path,
        class: "sidebar-item union-hub flex flex-col items-center justify-between text-base font-light w-1/3 #{current_page?(root_path) ? 'current-path' : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'}" do %>
    <%= show_svg('union-hub.svg') %>
    Union Hub
    <% end %>
    </a>

    <%= link_to user_profile_path,
        class: "sidebar-item my-profile flex flex-col items-center justify-between text-base font-light w-1/3 #{current_path?('/profile') ? 'current-path' : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'}" do %>
    <%= show_svg('profile.svg') %>
    My profile
    <% end %>

    <%= link_to user_membership_path,
        class: "sidebar-item membership flex flex-col items-center justify-between text-base font-light w-1/3 #{current_path?('/membership') ? 'current-path' : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'}" do %>
    <%= show_svg('membership.svg') %>
    Membership
    <% end %>
  </nav>
</div>

<!-- Static sidebar for desktop -->
<div class="hidden md:flex md:flex-shrink-0 mt-8">
  <div class="flex flex-col w-56">
    <!-- Sidebar component, swap this element with another sidebar if you like -->
    <nav class="flex-1 pr-2 space-y-1 bg-white fixed" style="width: inherit">
      <!-- Current: "bg-gray-100 text-gray-900", Default: "text-gray-600 hover:bg-gray-50 hover:text-gray-900" -->
      <%= link_to root_path,
        class: "sidebar-item union-hub flex items-center group rounded-r px-6 py-4 justify-between text-base font-light h-16 #{current_page?(root_path) ? 'current-path' : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'}" do %>
      Union Hub
      <%= show_svg('union-hub.svg') %>
      <% end %>
      </a>

      <%= link_to user_profile_path,
        class: "sidebar-item my-profile flex items-center group rounded-r px-6 py-4 justify-between text-base font-light h-16 #{current_path?('/profile') ? 'current-path' : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'}" do %>
      My profile
      <%= show_svg('profile.svg') %>
      <% end %>

      <%= link_to user_membership_path,
        class: "sidebar-item membership flex items-center group rounded-r px-6 py-4 justify-between text-base font-light h-16 #{current_path?('/membership') ? 'current-path' : 'text-gray-600 hover:bg-gray-50 hover:text-gray-900'}" do %>
      Membership
      <%= show_svg('membership.svg') %>
      <% end %>
    </nav>
  </div>
</div>

app/views/shared/_stripe_scripts.html.erb
<script>
  function intializeStripeConfiguration(){
    // Create a Stripe client.
    const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');

    // Create an instance of Elements.
    const elements = stripe.elements();

    // Custom styling can be passed to options when creating an Element.
    const style = {
      base: {
        color: '#32325d',
        fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
        fontSmoothing: 'antialiased',
        fontSize: '16px',
        '::placeholder': {
          color: '#aab7c4'
        }
      },
      invalid: {
        color: '#fa755a',
        iconColor: '#fa755a'
      }
    };

    // Create an instance of the card Element.
    const card = elements.create('card', {style: style});

    // Add an instance of the card Element into the `card-element` <div>.
    card.mount('#card-element');
    const submitPaymentButton = document.getElementById('submit-payment')
    const cardDisplayError = document.getElementById('card-errors');

    // Handle real-time validation errors from the card Element.
    card.addEventListener('change', function(event) {
      if (event.error) {
        cardDisplayError.textContent = event.error.message;
      } else {
        cardDisplayError.textContent = '';
        submitPaymentButton.removeAttribute("disabled", "disabled");
      }
    });

    const captchaDisplayError = document.getElementById('captcha-errors');

    function verifyCaptcha() {
      let isCaptchaValidated = false;
      const captchaField = document.getElementById('g-recaptcha-response');

      if (captchaField && captchaField.value.length == 0) {
          isCaptchaValidated = false;
          captchaDisplayError.textContent = 'Please verify that you are a Human.';
      } else {
          captchaDisplayError.textContent = '';
          isCaptchaValidated = true;
      }
      return isCaptchaValidated
    }

    // Handle form submission.
    const form = document.getElementById('payment-form');
    form.addEventListener('submit', function(event) {
      event.preventDefault();
      const isCaptchaValid = verifyCaptcha()

      if (isCaptchaValid) {

        // Get credit card holder information for Stripe
        const nameField = document.getElementById('name-field')
        const addressLine1Field = document.getElementById('address-line1-field')
        const addressCityField = document.getElementById('address-city-field')
        const addressZipField = document.getElementById('address-zip-field')
        const addressCountrySelect = document.getElementById('address-country-code-select')
        const data = {
          name: nameField.value,
          address_line1: addressLine1Field && addressLine1Field.value,
          address_city: addressCityField && addressCityField.value,
          address_zip: addressZipField && addressZipField.value,
          address_country: addressCountrySelect && addressCountrySelect.value
        };

        // remove null values since Stripe fails to process them
        Object.keys(data).forEach(function(key) {
          if (data[key] == undefined) {
            delete data[key]
          }
        })

        submitPaymentButton.setAttribute("disabled", "disabled");

        // create the card token passing data object
        stripe.createToken(card, data).then(function(result) {
          if (result.error) {
            // Inform the user if there was an error.
            const errorElement = document.getElementById('card-errors');
            errorElement.textContent = result.error.message;

            submitPaymentButton.removeAttribute("disabled", "disabled");
          } else {
            // Send the token to your server.
            stripeTokenHandler(result.token);
          }
        });
      }
    });

    // Submit the form with the token ID.
    function stripeTokenHandler(token) {
      // Insert the token ID into the form so it gets submitted to the server
      const form = document.getElementById('payment-form');
      const stripeHiddenInput = document.createElement('input');
      stripeHiddenInput.setAttribute('type', 'hidden');
      stripeHiddenInput.setAttribute('name', 'charge[stripe_token]');
      stripeHiddenInput.setAttribute('value', token.id);
      form.appendChild(stripeHiddenInput);

      // Submit the form
      form.submit();
    }
  }

  intializeStripeConfiguration()
</script>